import { Logistic } from '../interface/logistic.interface';

export const LogisticData: Logistic[] = [
  {
    id: 1,
    code: '0-1',
    name: '應援訓練',
    Mp: 0,
    Ammo: 145,
    Mre: 145,
    Part: 0,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 1,
    Quick_Reinforce: 1,
    Furniture_Coin: 0,
    time: 3000
  },
  {
    id: 2,
    code: '0-2',
    name: '梯隊集訓',
    Mp: 550,
    Ammo: 0,
    Mre: 0,
    Part: 350,
    IOP_Contract: 1,
    EQUIP_Contract: 0,
    Quick_Develop: 0,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 10800
  },
  {
    id: 3,
    code: '0-3',
    name: '特種支援',
    Mp: 900,
    Ammo: 900,
    Mre: 900,
    Part: 250,
    IOP_Contract: 0,
    EQUIP_Contract: 1,
    Quick_Develop: 0,
    Quick_Reinforce: 1,
    Furniture_Coin: 0,
    time: 43200
  },
  {
    id: 4,
    code: '0-4',
    name: '聯合演習',
    Mp: 0,
    Ammo: 1200,
    Mre: 800,
    Part: 750,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 0,
    Quick_Reinforce: 0,
    Furniture_Coin: 1,
    time: 86400
  },
  {
    id: 5,
    code: '1-1',
    name: '熱身運動',
    Mp: 10,
    Ammo: 30,
    Mre: 15,
    Part: 0,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 0,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 900
  },
  {
    id: 6,
    code: '1-2',
    name: '巡邏戒嚴',
    Mp: 0,
    Ammo: 40,
    Mre: 60,
    Part: 0,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 0,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 1800
  },
  {
    id: 7,
    code: '1-3',
    name: '傷患搬運',
    Mp: 30,
    Ammo: 0,
    Mre: 30,
    Part: 10,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 0,
    Quick_Reinforce: 1,
    Furniture_Coin: 0,
    time: 3600
  },
  {
    id: 8,
    code: '1-4',
    name: '全境搜查',
    Mp: 160,
    Ammo: 160,
    Mre: 0,
    Part: 0,
    IOP_Contract: 1,
    EQUIP_Contract: 0,
    Quick_Develop: 0,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 7200
  },
  {
    id: 9,
    code: '2-1',
    name: '前線偵查',
    Mp: 100,
    Ammo: 0,
    Mre: 0,
    Part: 30,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 0,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 2400
  },
  {
    id: 10,
    code: '2-2',
    name: '後方運輸',
    Mp: 60,
    Ammo: 200,
    Mre: 80,
    Part: 0,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 0,
    Quick_Reinforce: 1,
    Furniture_Coin: 0,
    time: 5400
  },
  {
    id: 11,
    code: '2-3',
    name: '工廠快遞',
    Mp: 10,
    Ammo: 10,
    Mre: 10,
    Part: 230,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 1,
    Quick_Reinforce: 1,
    Furniture_Coin: 0,
    time: 14400
  },
  {
    id: 12,
    code: '2-4',
    name: '採集數據',
    Mp: 0,
    Ammo: 250,
    Mre: 600,
    Part: 60,
    IOP_Contract: 1,
    EQUIP_Contract: 0,
    Quick_Develop: 0,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 21600
  },
  {
    id: 13,
    code: '3-1',
    name: '強化工事',
    Mp: 50,
    Ammo: 0,
    Mre: 75,
    Part: 0,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 0,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 1200
  },
  {
    id: 14,
    code: '3-2',
    name: '截獲密報',
    Mp: 0,
    Ammo: 120,
    Mre: 70,
    Part: 30,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 0,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 2700
  },
  {
    id: 15,
    code: '3-3',
    name: '交通管制',
    Mp: 0,
    Ammo: 300,
    Mre: 0,
    Part: 0,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 1,
    Quick_Reinforce: 1,
    Furniture_Coin: 0,
    time: 5400
  },
  {
    id: 16,
    code: '3-4',
    name: '封鎖密道',
    Mp: 0,
    Ammo: 0,
    Mre: 300,
    Part: 300,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 1,
    Quick_Reinforce: 1,
    Furniture_Coin: 0,
    time: 5400
  },
  {
    id: 17,
    code: '4-1',
    name: '視野支援',
    Mp: 0,
    Ammo: 185,
    Mre: 185,
    Part: 0,
    IOP_Contract: 0,
    EQUIP_Contract: 1,
    Quick_Develop: 0,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 3600
  },
  {
    id: 18,
    code: '4-2',
    name: '切斷補給',
    Mp: 0,
    Ammo: 0,
    Mre: 0,
    Part: 210,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 1,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 7200
  },
  {
    id: 19,
    code: '4-3',
    name: '竊取地圖',
    Mp: 800,
    Ammo: 550,
    Mre: 0,
    Part: 0,
    IOP_Contract: 1,
    EQUIP_Contract: 0,
    Quick_Develop: 0,
    Quick_Reinforce: 1,
    Furniture_Coin: 0,
    time: 21600
  },
  {
    id: 20,
    code: '4-4',
    name: '座標定位',
    Mp: 400,
    Ammo: 400,
    Mre: 400,
    Part: 150,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 1,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 28800
  },
  {
    id: 21,
    code: '5-1',
    name: '例行檢閱',
    Mp: 0,
    Ammo: 0,
    Mre: 100,
    Part: 45,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 0,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 1800
  },
  {
    id: 22,
    code: '5-2',
    name: '現場救援',
    Mp: 0,
    Ammo: 600,
    Mre: 300,
    Part: 0,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 0,
    Quick_Reinforce: 1,
    Furniture_Coin: 0,
    time: 9000
  },
  {
    id: 23,
    code: '5-3',
    name: '路線追蹤',
    Mp: 800,
    Ammo: 400,
    Mre: 400,
    Part: 0,
    IOP_Contract: 0,
    EQUIP_Contract: 1,
    Quick_Develop: 0,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 14400
  },
  {
    id: 24,
    code: '5-4',
    name: '維穩工作',
    Mp: 100,
    Ammo: 0,
    Mre: 0,
    Part: 700,
    IOP_Contract: 1,
    EQUIP_Contract: 0,
    Quick_Develop: 0,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 25200
  },
  {
    id: 25,
    code: '6-1',
    name: '協助救援',
    Mp: 300,
    Ammo: 300,
    Mre: 0,
    Part: 100,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 0,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 7200
  },
  {
    id: 26,
    code: '6-2',
    name: '遠程偵察',
    Mp: 0,
    Ammo: 200,
    Mre: 550,
    Part: 100,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 1,
    Quick_Reinforce: 1,
    Furniture_Coin: 0,
    time: 10800
  },
  {
    id: 27,
    code: '6-3',
    name: '提取科技',
    Mp: 0,
    Ammo: 0,
    Mre: 200,
    Part: 500,
    IOP_Contract: 0,
    EQUIP_Contract: 1,
    Quick_Develop: 0,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 18000
  },
  {
    id: 28,
    code: '6-4',
    name: '戰場搜索',
    Mp: 800,
    Ammo: 800,
    Mre: 800,
    Part: 0,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 0,
    Quick_Reinforce: 0,
    Furniture_Coin: 1,
    time: 43200
  },
  {
    id: 29,
    code: '7-1',
    name: '監視據點',
    Mp: 650,
    Ammo: 0,
    Mre: 650,
    Part: 0,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 0,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 9000
  },
  {
    id: 30,
    code: '7-2',
    name: '接應隊友',
    Mp: 0,
    Ammo: 650,
    Mre: 0,
    Part: 300,
    IOP_Contract: 1,
    EQUIP_Contract: 0,
    Quick_Develop: 0,
    Quick_Reinforce: 1,
    Furniture_Coin: 0,
    time: 14400
  },
  {
    id: 31,
    code: '7-3',
    name: '清理道路',
    Mp: 900,
    Ammo: 600,
    Mre: 600,
    Part: 0,
    IOP_Contract: 0,
    EQUIP_Contract: 1,
    Quick_Develop: 0,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 19800
  },
  {
    id: 32,
    code: '7-4',
    name: '追蹤傀儡',
    Mp: 250,
    Ammo: 250,
    Mre: 250,
    Part: 600,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 1,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 28800
  },
  {
    id: 33,
    code: '8-1',
    name: '籌集資料',
    Mp: 150,
    Ammo: 150,
    Mre: 150,
    Part: 0,
    IOP_Contract: 0,
    EQUIP_Contract: 1,
    Quick_Develop: 0,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 3600
  },
  {
    id: 34,
    code: '8-2',
    name: '解析碎片',
    Mp: 0,
    Ammo: 0,
    Mre: 0,
    Part: 450,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 0,
    Quick_Reinforce: 1,
    Furniture_Coin: 0,
    time: 10800
  },
  {
    id: 35,
    code: '8-3',
    name: '勘探現場',
    Mp: 400,
    Ammo: 800,
    Mre: 800,
    Part: 0,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 1,
    Quick_Reinforce: 1,
    Furniture_Coin: 0,
    time: 21600
  },
  {
    id: 36,
    code: '8-4',
    name: '修訂路線',
    Mp: 1500,
    Ammo: 400,
    Mre: 400,
    Part: 100,
    IOP_Contract: 1,
    EQUIP_Contract: 0,
    Quick_Develop: 0,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 32400
  },
  {
    id: 37,
    code: '9-1',
    name: '清理哨站',
    Mp: 0,
    Ammo: 0,
    Mre: 100,
    Part: 50,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 0,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 1800
  },
  {
    id: 38,
    code: '9-2',
    name: '探測信號',
    Mp: 180,
    Ammo: 0,
    Mre: 180,
    Part: 100,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 1,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 5400
  },
  {
    id: 39,
    code: '9-3',
    name: '快速營救',
    Mp: 750,
    Ammo: 750,
    Mre: 0,
    Part: 0,
    IOP_Contract: 1,
    EQUIP_Contract: 0,
    Quick_Develop: 0,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 16200
  },
  {
    id: 40,
    code: '9-4',
    name: '緊急壓制',
    Mp: 500,
    Ammo: 900,
    Mre: 900,
    Part: 0,
    IOP_Contract: 0,
    EQUIP_Contract: 1,
    Quick_Develop: 0,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 25200
  },
  {
    id: 41,
    code: '10-1',
    name: '協助驗證',
    Mp: 140,
    Ammo: 200,
    Mre: 0,
    Part: 0,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 0,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 2400
  },
  {
    id: 42,
    code: '10-2',
    name: '前線支援',
    Mp: 0,
    Ammo: 240,
    Mre: 180,
    Part: 0,
    IOP_Contract: 1,
    EQUIP_Contract: 0,
    Quick_Develop: 1,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 6000
  },
  {
    id: 43,
    code: '10-3',
    name: '腹地偵查',
    Mp: 0,
    Ammo: 480,
    Mre: 480,
    Part: 300,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 1,
    Quick_Reinforce: 1,
    Furniture_Coin: 0,
    time: 19200
  },
  {
    id: 44,
    code: '10-4',
    name: '奪取通訊',
    Mp: 660,
    Ammo: 660,
    Mre: 660,
    Part: 330,
    IOP_Contract: 0,
    EQUIP_Contract: 1,
    Quick_Develop: 0,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 36000
  },
  {
    id: 45,
    code: '11-1',
    name: '人員輸送',
    Mp: 350,
    Ammo: 1050,
    Mre: 0,
    Part: 0,
    IOP_Contract: 1,
    EQUIP_Contract: 1,
    Quick_Develop: 0,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 14400
  },
  {
    id: 46,
    code: '11-2',
    name: '破解監視',
    Mp: 360,
    Ammo: 540,
    Mre: 540,
    Part: 0,
    IOP_Contract: 1,
    EQUIP_Contract: 0,
    Quick_Develop: 0,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 14400
  },
  {
    id: 47,
    code: '11-3',
    name: '外觀偽裝',
    Mp: 0,
    Ammo: 750,
    Mre: 1500,
    Part: 250,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 0,
    Quick_Reinforce: 1,
    Furniture_Coin: 0,
    time: 28800
  },
  {
    id: 48,
    code: '11-4',
    name: '突擊支援',
    Mp: 0,
    Ammo: 1650,
    Mre: 0,
    Part: 900,
    IOP_Contract: 0,
    EQUIP_Contract: 0,
    Quick_Develop: 1,
    Quick_Reinforce: 0,
    Furniture_Coin: 0,
    time: 36000
  }
];
