import { Logistic } from '../interface/logistic.interface';

export const LogisticData: Logistic[] = [
  {
    id: 1,
    code: '0-1',
    name: '應援訓練',
    mp: 0,
    ammo: 145,
    mre: 145,
    part: 0,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 1,
    quick_reinforce: 1,
    furniture_coin: 0,
    time: 3000
  },
  {
    id: 2,
    code: '0-2',
    name: '梯隊集訓',
    mp: 550,
    ammo: 0,
    mre: 0,
    part: 350,
    iop_contract: 1,
    equip_contract: 0,
    quick_develop: 0,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 10800
  },
  {
    id: 3,
    code: '0-3',
    name: '特種支援',
    mp: 900,
    ammo: 900,
    mre: 900,
    part: 250,
    iop_contract: 0,
    equip_contract: 1,
    quick_develop: 0,
    quick_reinforce: 1,
    furniture_coin: 0,
    time: 43200
  },
  {
    id: 4,
    code: '0-4',
    name: '聯合演習',
    mp: 0,
    ammo: 1200,
    mre: 800,
    part: 750,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 0,
    quick_reinforce: 0,
    furniture_coin: 1,
    time: 86400
  },
  {
    id: 5,
    code: '1-1',
    name: '熱身運動',
    mp: 10,
    ammo: 30,
    mre: 15,
    part: 0,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 0,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 900
  },
  {
    id: 6,
    code: '1-2',
    name: '巡邏戒嚴',
    mp: 0,
    ammo: 40,
    mre: 60,
    part: 0,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 0,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 1800
  },
  {
    id: 7,
    code: '1-3',
    name: '傷患搬運',
    mp: 30,
    ammo: 0,
    mre: 30,
    part: 10,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 0,
    quick_reinforce: 1,
    furniture_coin: 0,
    time: 3600
  },
  {
    id: 8,
    code: '1-4',
    name: '全境搜查',
    mp: 160,
    ammo: 160,
    mre: 0,
    part: 0,
    iop_contract: 1,
    equip_contract: 0,
    quick_develop: 0,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 7200
  },
  {
    id: 9,
    code: '2-1',
    name: '前線偵查',
    mp: 100,
    ammo: 0,
    mre: 0,
    part: 30,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 0,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 2400
  },
  {
    id: 10,
    code: '2-2',
    name: '後方運輸',
    mp: 60,
    ammo: 200,
    mre: 80,
    part: 0,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 0,
    quick_reinforce: 1,
    furniture_coin: 0,
    time: 5400
  },
  {
    id: 11,
    code: '2-3',
    name: '工廠快遞',
    mp: 10,
    ammo: 10,
    mre: 10,
    part: 230,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 1,
    quick_reinforce: 1,
    furniture_coin: 0,
    time: 14400
  },
  {
    id: 12,
    code: '2-4',
    name: '採集數據',
    mp: 0,
    ammo: 250,
    mre: 600,
    part: 60,
    iop_contract: 1,
    equip_contract: 0,
    quick_develop: 0,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 21600
  },
  {
    id: 13,
    code: '3-1',
    name: '強化工事',
    mp: 50,
    ammo: 0,
    mre: 75,
    part: 0,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 0,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 1200
  },
  {
    id: 14,
    code: '3-2',
    name: '截獲密報',
    mp: 0,
    ammo: 120,
    mre: 70,
    part: 30,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 0,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 2700
  },
  {
    id: 15,
    code: '3-3',
    name: '交通管制',
    mp: 0,
    ammo: 300,
    mre: 0,
    part: 0,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 1,
    quick_reinforce: 1,
    furniture_coin: 0,
    time: 5400
  },
  {
    id: 16,
    code: '3-4',
    name: '封鎖密道',
    mp: 0,
    ammo: 0,
    mre: 300,
    part: 300,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 1,
    quick_reinforce: 1,
    furniture_coin: 0,
    time: 5400
  },
  {
    id: 17,
    code: '4-1',
    name: '視野支援',
    mp: 0,
    ammo: 185,
    mre: 185,
    part: 0,
    iop_contract: 0,
    equip_contract: 1,
    quick_develop: 0,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 3600
  },
  {
    id: 18,
    code: '4-2',
    name: '切斷補給',
    mp: 0,
    ammo: 0,
    mre: 0,
    part: 210,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 1,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 7200
  },
  {
    id: 19,
    code: '4-3',
    name: '竊取地圖',
    mp: 800,
    ammo: 550,
    mre: 0,
    part: 0,
    iop_contract: 1,
    equip_contract: 0,
    quick_develop: 0,
    quick_reinforce: 1,
    furniture_coin: 0,
    time: 21600
  },
  {
    id: 20,
    code: '4-4',
    name: '座標定位',
    mp: 400,
    ammo: 400,
    mre: 400,
    part: 150,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 1,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 28800
  },
  {
    id: 21,
    code: '5-1',
    name: '例行檢閱',
    mp: 0,
    ammo: 0,
    mre: 100,
    part: 45,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 0,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 1800
  },
  {
    id: 22,
    code: '5-2',
    name: '現場救援',
    mp: 0,
    ammo: 600,
    mre: 300,
    part: 0,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 0,
    quick_reinforce: 1,
    furniture_coin: 0,
    time: 9000
  },
  {
    id: 23,
    code: '5-3',
    name: '路線追蹤',
    mp: 800,
    ammo: 400,
    mre: 400,
    part: 0,
    iop_contract: 0,
    equip_contract: 1,
    quick_develop: 0,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 14400
  },
  {
    id: 24,
    code: '5-4',
    name: '維穩工作',
    mp: 100,
    ammo: 0,
    mre: 0,
    part: 700,
    iop_contract: 1,
    equip_contract: 0,
    quick_develop: 0,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 25200
  },
  {
    id: 25,
    code: '6-1',
    name: '協助救援',
    mp: 300,
    ammo: 300,
    mre: 0,
    part: 100,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 0,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 7200
  },
  {
    id: 26,
    code: '6-2',
    name: '遠程偵察',
    mp: 0,
    ammo: 200,
    mre: 550,
    part: 100,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 1,
    quick_reinforce: 1,
    furniture_coin: 0,
    time: 10800
  },
  {
    id: 27,
    code: '6-3',
    name: '提取科技',
    mp: 0,
    ammo: 0,
    mre: 200,
    part: 500,
    iop_contract: 0,
    equip_contract: 1,
    quick_develop: 0,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 18000
  },
  {
    id: 28,
    code: '6-4',
    name: '戰場搜索',
    mp: 800,
    ammo: 800,
    mre: 800,
    part: 0,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 0,
    quick_reinforce: 0,
    furniture_coin: 1,
    time: 43200
  },
  {
    id: 29,
    code: '7-1',
    name: '監視據點',
    mp: 650,
    ammo: 0,
    mre: 650,
    part: 0,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 0,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 9000
  },
  {
    id: 30,
    code: '7-2',
    name: '接應隊友',
    mp: 0,
    ammo: 650,
    mre: 0,
    part: 300,
    iop_contract: 1,
    equip_contract: 0,
    quick_develop: 0,
    quick_reinforce: 1,
    furniture_coin: 0,
    time: 14400
  },
  {
    id: 31,
    code: '7-3',
    name: '清理道路',
    mp: 900,
    ammo: 600,
    mre: 600,
    part: 0,
    iop_contract: 0,
    equip_contract: 1,
    quick_develop: 0,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 19800
  },
  {
    id: 32,
    code: '7-4',
    name: '追蹤傀儡',
    mp: 250,
    ammo: 250,
    mre: 250,
    part: 600,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 1,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 28800
  },
  {
    id: 33,
    code: '8-1',
    name: '籌集資料',
    mp: 150,
    ammo: 150,
    mre: 150,
    part: 0,
    iop_contract: 0,
    equip_contract: 1,
    quick_develop: 0,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 3600
  },
  {
    id: 34,
    code: '8-2',
    name: '解析碎片',
    mp: 0,
    ammo: 0,
    mre: 0,
    part: 450,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 0,
    quick_reinforce: 1,
    furniture_coin: 0,
    time: 10800
  },
  {
    id: 35,
    code: '8-3',
    name: '勘探現場',
    mp: 400,
    ammo: 800,
    mre: 800,
    part: 0,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 1,
    quick_reinforce: 1,
    furniture_coin: 0,
    time: 21600
  },
  {
    id: 36,
    code: '8-4',
    name: '修訂路線',
    mp: 1500,
    ammo: 400,
    mre: 400,
    part: 100,
    iop_contract: 1,
    equip_contract: 0,
    quick_develop: 0,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 32400
  },
  {
    id: 37,
    code: '9-1',
    name: '清理哨站',
    mp: 0,
    ammo: 0,
    mre: 100,
    part: 50,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 0,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 1800
  },
  {
    id: 38,
    code: '9-2',
    name: '探測信號',
    mp: 180,
    ammo: 0,
    mre: 180,
    part: 100,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 1,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 5400
  },
  {
    id: 39,
    code: '9-3',
    name: '快速營救',
    mp: 750,
    ammo: 750,
    mre: 0,
    part: 0,
    iop_contract: 1,
    equip_contract: 0,
    quick_develop: 0,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 16200
  },
  {
    id: 40,
    code: '9-4',
    name: '緊急壓制',
    mp: 500,
    ammo: 900,
    mre: 900,
    part: 0,
    iop_contract: 0,
    equip_contract: 1,
    quick_develop: 0,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 25200
  },
  {
    id: 41,
    code: '10-1',
    name: '協助驗證',
    mp: 140,
    ammo: 200,
    mre: 0,
    part: 0,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 0,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 2400
  },
  {
    id: 42,
    code: '10-2',
    name: '前線支援',
    mp: 0,
    ammo: 240,
    mre: 180,
    part: 0,
    iop_contract: 1,
    equip_contract: 0,
    quick_develop: 1,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 6000
  },
  {
    id: 43,
    code: '10-3',
    name: '腹地偵查',
    mp: 0,
    ammo: 480,
    mre: 480,
    part: 300,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 1,
    quick_reinforce: 1,
    furniture_coin: 0,
    time: 19200
  },
  {
    id: 44,
    code: '10-4',
    name: '奪取通訊',
    mp: 660,
    ammo: 660,
    mre: 660,
    part: 330,
    iop_contract: 0,
    equip_contract: 1,
    quick_develop: 0,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 36000
  },
  {
    id: 45,
    code: '11-1',
    name: '人員輸送',
    mp: 350,
    ammo: 1050,
    mre: 0,
    part: 0,
    iop_contract: 1,
    equip_contract: 1,
    quick_develop: 0,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 14400
  },
  {
    id: 46,
    code: '11-2',
    name: '破解監視',
    mp: 360,
    ammo: 540,
    mre: 540,
    part: 0,
    iop_contract: 1,
    equip_contract: 0,
    quick_develop: 0,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 14400
  },
  {
    id: 47,
    code: '11-3',
    name: '外觀偽裝',
    mp: 0,
    ammo: 750,
    mre: 1500,
    part: 250,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 0,
    quick_reinforce: 1,
    furniture_coin: 0,
    time: 28800
  },
  {
    id: 48,
    code: '11-4',
    name: '突擊支援',
    mp: 0,
    ammo: 1650,
    mre: 0,
    part: 900,
    iop_contract: 0,
    equip_contract: 0,
    quick_develop: 1,
    quick_reinforce: 0,
    furniture_coin: 0,
    time: 36000
  }
];
