language: node_js

node_js: node

branches:
  only:
  - master

before_install:
- cd logistics

install:
- npm install

script:
- ng build --prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

cache:
  directories:
    - node_modules